### ISSUE TITLE
Enchance Home Page

### ISSUE THREAD

**Issue by arnoGH** [JamBSquared/Carpool#4]
Currently, the home page HTML file is very basic. It is missing a lot of buttons and functionality needed for a proper home page. 

Populate the HTML file with everything needed and add a nice design to the page in general. Include:
- settings button
- a welcome message with user's name
- notification icon if someone is interested in user's route
- redesign "Search for Carpool" and "Add New Route" buttons

**Comment by jyan17** [comment]
Arno, I'll be finishing the rest of this on Sunday since I have work all day Saturday and I don't get home until after 11pm. But check your Discord because I have some questions on how you want the design to be and where the files are linked.
